sudo: required

services:
  - docker

before_install:
  - docker build -t macpie/elb:travis .

script:
  - docker run macpie/elb:travis /bin/sh -c "rebar3 xref"
  - docker run macpie/elb:travis /bin/sh -c "rebar3 eunit"
  - docker run macpie/elb:travis /bin/sh -c "rebar3 dialyzer"
  - docker run macpie/elb:travis /bin/sh -c "rebar3 ct"
